/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionemagazzino;

import java.sql.*;

/**
 *
 * @author faroe
 */
public class ElencoProdotti extends javax.swing.JInternalFrame {

    /**
     * Creates new form ElencoProdotti
     */
    public ElencoProdotti() {
        initComponents();
        caricaDati();
    }

    private void caricaDati() {

        //dati per accesso
        //effettuare la query verso il database
        //recupero dati nel ResultSet
        //visualizzare i dati
        //chiudere la connessione
        //parametri per accesso al database
        String host = "localhost"; //127.0.0.1
        int port = 3306; //default per mysql
        String dbName = "cifi";
        String userDB = "cifi";
        String passwordDB = "java-2021";

        //driver per accesso al database
        String driver = "com.mysql.cj.jdbc.Driver";

        //stringa di connessione al database MySQL
        String url = "jdbc:mysql://" + host + ":" + port + "/" + dbName;

        try {
            //load del driver
            Class.forName(driver);

            //effettuo la connessione al database
            Connection connection = DriverManager.getConnection(url,userDB,passwordDB);

            //costruisco la sintassi sql per dialogare con il database
            String sql = "select * FROM prodotti";

            //istanzio l'oggetto st per dialogare con il database
            Statement st = connection.createStatement();

            //estraggo i dati dal database
            ResultSet rs = st.executeQuery(sql);

            String txt = "codice\tnome\tdescrizione\tprezzo\tgiacenza";
            while (rs.next()) {
                int codice = rs.getInt("Codice");
                String nome = rs.getString("Nome");
                String descrizione = rs.getString("Descrizione");
                double prezzo = rs.getDouble("Prezzo");
                int giacenza = rs.getInt("Giacenza");

                txt += "\n"+codice + "\t" + nome + "\t" + descrizione + "\t" + prezzo + "\t" + giacenza;
            }

            rs.close(); //chiudo il recordset
            st.close(); //rilascio la risorsa st					
            connection.close(); //finalizzo la connessione al database

            txtElencoProdotti.setText(txt);
            
            
        } catch (ClassNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtElencoProdotti = new javax.swing.JTextArea();
        lblElementiTrovati = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Elenco Prodotti");

        lblTitolo.setText("Elenco Prodotti");

        txtElencoProdotti.setColumns(20);
        txtElencoProdotti.setRows(5);
        txtElencoProdotti.setEnabled(false);
        jScrollPane1.setViewportView(txtElencoProdotti);

        lblElementiTrovati.setText("Elementi trovati: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(lblTitolo)
                .addContainerGap(202, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblElementiTrovati)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblElementiTrovati)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblElementiTrovati;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextArea txtElencoProdotti;
    // End of variables declaration//GEN-END:variables
}
