/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionemagazzino;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author catal
 */
public class EliminaProdotto extends javax.swing.JInternalFrame {

    String host = "localhost"; // 127.0.0.1
    int port = 3306; // default per mysql
    String dbName = "cifi";
    String userDB = "cifi";
    String passwordDB = "java-2021";

    // driver per accesso al database
    String driver = "com.mysql.cj.jdbc.Driver";

    // stringa di connessione al database MySQL
    String url = "jdbc:mysql://" + host + ":" + port + "/" + dbName;
    
    /**
     * Creates new form EliminaProdotto
     */
    public EliminaProdotto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        lblCodice2 = new javax.swing.JLabel();
        lblCodice3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPrezzo = new javax.swing.JTextField();
        lblCodice = new javax.swing.JLabel();
        lblCodice4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrizione = new javax.swing.JTextArea();
        txtGiacenza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodice = new javax.swing.JTextField();
        txtCerca = new javax.swing.JTextField();
        btnInvia = new javax.swing.JButton();
        btnCerca = new javax.swing.JButton();
        lnlNobe = new javax.swing.JLabel();
        btnCancella = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Elimina Prodotto");

        txtNome.setEnabled(false);

        lblCodice2.setText("Descrizione");

        lblCodice3.setText("Prezzo");

        jLabel1.setText("Elimina  Prodotto");

        txtPrezzo.setEnabled(false);

        lblCodice.setText("Codice");

        lblCodice4.setText("Giacenza");

        txtDescrizione.setColumns(20);
        txtDescrizione.setRows(5);
        txtDescrizione.setEnabled(false);
        jScrollPane1.setViewportView(txtDescrizione);

        txtGiacenza.setEnabled(false);

        jLabel2.setText("Codice");

        txtCodice.setEnabled(false);

        btnInvia.setText("Elimina");
        btnInvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInviaActionPerformed(evt);
            }
        });

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        lnlNobe.setText("Nome");

        btnCancella.setText("Cancella");
        btnCancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancellaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCodice3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCodice4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnInvia)
                                                .addGap(38, 38, 38)
                                                .addComponent(btnCancella))
                                            .addComponent(txtGiacenza, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCodice2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lnlNobe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCodice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodice, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCerca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerca)
                            .addComponent(jLabel1))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodice)
                    .addComponent(txtCodice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnlNobe)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodice2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodice3)
                    .addComponent(txtPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodice4)
                    .addComponent(txtGiacenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvia)
                    .addComponent(btnCancella))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInviaActionPerformed
        // TODO add your handling code here:
        // parametri per accesso al database
        if (JOptionPane.showConfirmDialog(this, "Eliminare il prodotto scelto?") != 0)
            return;
        
        try {
            // load del driver
            Class.forName(driver);

            // effettuo la connessione al database
            Connection connection = DriverManager.getConnection(url, userDB, passwordDB);

            // costruisco la sintassi sql per dialogare con il database
            String sql = "Delete from prodotti where codice=?";

            // istanzio l'oggetto st per dialogare con il database
            PreparedStatement ps = connection.prepareStatement(sql);

            ps.setInt(1, Integer.parseInt(txtCodice.getText()));

            // estraggo i dati dal database
            int rows = ps.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Eliminazione dati avvenuta con successo");
            } else {
                JOptionPane.showMessageDialog(this, "Eliminazione fallita");
            }

            ps.close(); // rilascio la risorsa st
            connection.close(); // finalizzo la connessione al database
            resetForm();
        } catch (ClassNotFoundException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnInviaActionPerformed

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        // TODO add your handling code here:
        // parametri per accesso al database

        try {
            // load del driver
            Class.forName(driver);

            // effettuo la connessione al database
            Connection connection = DriverManager.getConnection(url, userDB, passwordDB);

            // costruisco la sintassi sql per dialogare con il database
            String sql = "Select * from prodotti where codice=?";

            // istanzio l'oggetto st per dialogare con il database
            PreparedStatement ps = connection.prepareStatement(sql);

            ps.setInt(1, Integer.parseInt(txtCerca.getText()));

            // estraggo i dati dal database
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                txtCodice.setText(rs.getInt("Codice")+"");
                txtNome.setText(rs.getString("Nome"));
                txtDescrizione.setText(rs.getString("Descrizione"));
                txtPrezzo.setText(rs.getDouble("Prezzo")+"");
                txtGiacenza.setText(rs.getInt("Giacenza")+"");

            } else {
                JOptionPane.showMessageDialog(this, "Prodotto non trovato");
                resetForm();
            }
            rs.close();
            ps.close(); // rilascio la risorsa st
            connection.close(); // finalizzo la connessione al database

        } catch (ClassNotFoundException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnCercaActionPerformed

    private void btnCancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancellaActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(this, "Eliminare tutti i dati?") == 0) {
            resetForm();
        }
    }//GEN-LAST:event_btnCancellaActionPerformed
void resetForm() {
        txtCodice.setText("");
        txtNome.setText("");
        txtDescrizione.setText("");
        txtPrezzo.setText("");
        txtGiacenza.setText("");
txtCerca.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancella;
    private javax.swing.JButton btnCerca;
    private javax.swing.JButton btnInvia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodice;
    private javax.swing.JLabel lblCodice2;
    private javax.swing.JLabel lblCodice3;
    private javax.swing.JLabel lblCodice4;
    private javax.swing.JLabel lnlNobe;
    private javax.swing.JTextField txtCerca;
    private javax.swing.JTextField txtCodice;
    private javax.swing.JTextArea txtDescrizione;
    private javax.swing.JTextField txtGiacenza;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrezzo;
    // End of variables declaration//GEN-END:variables
}
