/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.Categoria;
import model.DaoCategoria;
import model.DaoProdotto;
import model.Prodotto;

/**
 *
 * @author faroe
 */
public class ElencoProdotti extends javax.swing.JInternalFrame {

    private Categoria categoria;
    
    public ElencoProdotti() {
        initComponents();
        caricaDati();
        loadCategorie();
    }

    private void caricaDati() {
        
        DaoProdotto dao = new DaoProdotto();
        
        String txt="";
        ArrayList<Prodotto> lista;
                
        if(categoria != null)
            lista = dao.getAll(categoria.getId());
        else
            lista = dao.getAll();
                    
        for(Prodotto p : lista)
            txt += (txt.length()!=0 ? "\n" : "") +p.toString();
        
        lblElementiTrovati.setText("Elementi trovati"+lista.size());
        
        txtElencoProdotti.setText(txt);

    }
    
    void loadCategorie(){
    
    if (cbxCategoria.getModel().getSize()!=0)
        return;
    
     DaoCategoria dao = new DaoCategoria();
     ArrayList<Categoria> elenco = dao.getAll();
     
     cbxCategoria.addItem("Tutti i prodotti");
    
    for(Categoria c : elenco)
        cbxCategoria.addItem(c.getNome());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtElencoProdotti = new javax.swing.JTextArea();
        lblElementiTrovati = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        btnCerca = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Elenco Prodotti");

        lblTitolo.setText("Elenco Prodotti");

        txtElencoProdotti.setColumns(20);
        txtElencoProdotti.setRows(5);
        txtElencoProdotti.setEnabled(false);
        jScrollPane1.setViewportView(txtElencoProdotti);

        lblElementiTrovati.setText("Elementi trovati: ");

        jLabel3.setText("Cerca per Categoria");

        btnCerca.setText("Cerca");
        btnCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCercaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblElementiTrovati)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitolo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerca)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblElementiTrovati)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCercaActionPerformed
        
        DaoCategoria dao = new DaoCategoria();        
                
        if(cbxCategoria.getSelectedIndex()!=0)
        categoria = dao.getByNome((String)cbxCategoria.getSelectedItem());
        else
            categoria = null;

        caricaDati();
        
    }//GEN-LAST:event_btnCercaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerca;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblElementiTrovati;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextArea txtElencoProdotti;
    // End of variables declaration//GEN-END:variables
}
