/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.Categoria;
import model.DaoCategoria;

/**
 *
 * @author faroe
 */
public class ElencoCategorie extends javax.swing.JInternalFrame {

    /**
     * Creates new form ElencoProdotti
     */
    public ElencoCategorie() {
        initComponents();
        caricaDati();
    }

    private void caricaDati() {

        DaoCategoria dao = new DaoCategoria();
        
        ArrayList<Categoria> lista = dao.getAll();
        
        lblElementiTrovati.setText("Elementi trovati: "+lista.size());        
        
        String txt="";
        for(Categoria c : lista)
            txt += (txt.length()!=0 ? "\n" : "") +c.toString();
        
        txtElencoProdotti.setText(txt);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitolo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtElencoProdotti = new javax.swing.JTextArea();
        lblElementiTrovati = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Elenco Categorie");

        lblTitolo.setText("Elenco Categorie");

        txtElencoProdotti.setColumns(20);
        txtElencoProdotti.setRows(5);
        txtElencoProdotti.setEnabled(false);
        jScrollPane1.setViewportView(txtElencoProdotti);

        lblElementiTrovati.setText("Elementi trovati: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(lblTitolo)
                .addContainerGap(193, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblElementiTrovati)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitolo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblElementiTrovati)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblElementiTrovati;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextArea txtElencoProdotti;
    // End of variables declaration//GEN-END:variables
}
