/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author faroe
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        mnuProdotti = new javax.swing.JMenu();
        mnuElencoProdotti = new javax.swing.JMenuItem();
        mnuNuovoProdotto = new javax.swing.JMenuItem();
        mnuModificaProdotto = new javax.swing.JMenuItem();
        mnuEliminaProdotto = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuNuovaCategoria = new javax.swing.JMenuItem();
        mnuModificaCategoria = new javax.swing.JMenuItem();
        mnuEliminaCategoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        mnuProdotti.setText("Prodotti");

        mnuElencoProdotti.setText("Elenco");
        mnuElencoProdotti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuElencoProdottiActionPerformed(evt);
            }
        });
        mnuProdotti.add(mnuElencoProdotti);

        mnuNuovoProdotto.setText("Nuovo");
        mnuNuovoProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuovoProdottoActionPerformed(evt);
            }
        });
        mnuProdotti.add(mnuNuovoProdotto);

        mnuModificaProdotto.setText("Modifica");
        mnuModificaProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificaProdottoActionPerformed(evt);
            }
        });
        mnuProdotti.add(mnuModificaProdotto);

        mnuEliminaProdotto.setText("Elimina");
        mnuEliminaProdotto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminaProdottoActionPerformed(evt);
            }
        });
        mnuProdotti.add(mnuEliminaProdotto);

        menuBar.add(mnuProdotti);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jMenu1.setText("Categorie");

        jMenuItem1.setText("Elenco");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mnuNuovaCategoria.setText("Nuovo");
        mnuNuovaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuovaCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuovaCategoria);

        mnuModificaCategoria.setText("Modifica");
        mnuModificaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificaCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuModificaCategoria);

        mnuEliminaCategoria.setText("Elimina");
        mnuEliminaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminaCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEliminaCategoria);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuElencoProdottiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuElencoProdottiActionPerformed
        // TODO add your handling code here:
        
        ElencoProdotti f = new ElencoProdotti();
        f.setVisible(true);
        this.desktopPane.add(f);
        
    }//GEN-LAST:event_mnuElencoProdottiActionPerformed

    private void mnuNuovoProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuovoProdottoActionPerformed
        // TODO add your handling code here:
        NuovoProdotto f = new NuovoProdotto();
        f.setVisible(true);
        this.desktopPane.add(f);
    }//GEN-LAST:event_mnuNuovoProdottoActionPerformed

    private void mnuModificaProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificaProdottoActionPerformed
        // TODO add your handling code here:
        ModificaProdotto f = new ModificaProdotto();
        f.setVisible(true);
        this.desktopPane.add(f);
    }//GEN-LAST:event_mnuModificaProdottoActionPerformed

    private void mnuEliminaProdottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminaProdottoActionPerformed
        // TODO add your handling code here:
        
        EliminaProdotto f = new EliminaProdotto();
        f.setVisible(true);
        this.desktopPane.add(f);
    }//GEN-LAST:event_mnuEliminaProdottoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        ElencoCategorie f = new ElencoCategorie();
        f.setVisible(true);
        this.desktopPane.add(f);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuNuovaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuovaCategoriaActionPerformed
        // TODO add your handling code here:
        NuovaCategoria f = new NuovaCategoria();
        f.setVisible(true);
        this.desktopPane.add(f);
    }//GEN-LAST:event_mnuNuovaCategoriaActionPerformed

    private void mnuModificaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificaCategoriaActionPerformed
        // TODO add your handling code here:
        ModificaCategoria f = new ModificaCategoria();
        f.setVisible(true);
        this.desktopPane.add(f);
    }//GEN-LAST:event_mnuModificaCategoriaActionPerformed

    private void mnuEliminaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminaCategoriaActionPerformed
        // TODO add your handling code here:
         EliminaCategoria f = new EliminaCategoria();
        f.setVisible(true);
        this.desktopPane.add(f);
        
    }//GEN-LAST:event_mnuEliminaCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuElencoProdotti;
    private javax.swing.JMenuItem mnuEliminaCategoria;
    private javax.swing.JMenuItem mnuEliminaProdotto;
    private javax.swing.JMenuItem mnuModificaCategoria;
    private javax.swing.JMenuItem mnuModificaProdotto;
    private javax.swing.JMenuItem mnuNuovaCategoria;
    private javax.swing.JMenuItem mnuNuovoProdotto;
    private javax.swing.JMenu mnuProdotti;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
